INSERT INTO questions (question, answer_a, answer_b, answer_c, answer_d, correct_answer, time_limit)
VALUES

  ('This author received the Pulitzer Prize in 1977 for his journalistic work, which was later turned into a famous novel about slavery.', 'James Baldwin', 'Alex Haley', 'Toni Morrison', 'Langston Hughes', 'B', 30),
  ('In 1966, the U.S. Supreme Court reversed the conviction of this man due to police misconduct during his arrest.', 'George W. Bush', 'Ernesto Miranda', 'Martin Luther King Jr.', 'Ted Bundy', 'B', 30),
  ('The first major conflict over the trade of a substance derived from a flower began in 1839.', 'Rose', 'Tulip', 'Poppy', 'Sunflower', 'C', 30),
  ('This island is unique because its territory is part of three different countries.', 'Java', 'Borneo', 'Greenland', 'Hispaniola', 'B', 30),
  ('After having a baby in Paris, Marjorie Karmel thanked this man and co-founded an influential birthing organization named after him.', 'Dr. William Sears', 'Dr. Fernand Lamaze', 'Dr. Spock', 'Dr. Benjamin Spock', 'B', 30),
  ('The last time in U.S. history when no former presidents were alive occurred during his term.', 'Lyndon B. Johnson', 'Richard Nixon', 'John F. Kennedy', 'Dwight D. Eisenhower', 'B', 30),
  ('This is the only continent in the world with no active volcanoes.', 'South America', 'Europe', 'Australia', 'North America', 'C', 20),
  ('Very little is known about this person’s life, but she is famous for disappearing after spending nine days in 1587.', 'Pocahontas', 'Virginia Dare', 'Cleopatra', 'Elizabeth I', 'B', 30),
  ('In 1981, this businessman’s company introduced the Customer Satisfaction Index (CSI) that has become widely recognized.', 'Howard Schultz', 'J.D. Power', 'Steve Jobs', 'Bill Gates', 'B', 30),
  ('The first movie in this series features a cyborg character who only speaks 133 words across 21 lines.', 'Aliens', 'The Terminator', 'Predator', 'Robocop', 'B', 20),
  ('In 1951, this Humphrey Bogart movie, adapted from a novel, tells the story of a riverboat captain in Africa.', 'Casablanca', 'The African Queen', 'The Maltese Falcon', 'The Big Sleep', 'B', 30),
  ('This term, meaning a close companion, comes from the Latin phrase "with whom you would break bread."', 'Amigo', 'Companion', 'Mate', 'Comrade', 'B', 20),
  ('Born in Connecticut in 1800 and executed for treason in 1859, this man was a radical abolitionist.', 'John Brown', 'Robert E. Lee', 'Abraham Lincoln', 'Frederick Douglass', 'A', 30),
  ('This garment, worn by some Muslim women, covers the hair and neck while leaving the face exposed.', 'Burqa', 'Hijab', 'Chador', 'Niqab', 'B', 20),
  ('The name of this news agency translates to "peninsula" and refers to the Arabian Peninsula.', 'Al Jazeera', 'BBC', 'Reuters', 'CNN', 'A', 30),
  ('The original title of this 1895 novel was "The Chronic Argonauts," written by a famous British author.', 'The Invisible Man', 'The War of the Worlds', 'The Time Machine', 'The Island of Doctor Moreau', 'C', 30),
  ('This country’s government has been led by figures such as Yusof Ishak, Benjamin Sheares, and Lee Kuan Yew.', 'Malaysia', 'Indonesia', 'Singapore', 'Thailand', 'C', 30),
  ('He still holds the record for being the tallest U.S. president, even after more than 150 years since his time in office.', 'Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John F. Kennedy', 'C', 30),
  ('In just 3 1/2 years, this man rose from mayor of Buffalo to governor of New York and eventually became president of the U.S.', 'Theodore Roosevelt', 'Grover Cleveland', 'Franklin Pierce', 'Andrew Johnson', 'B', 30),
  ('This 1874 political group was formed to advocate for increasing the money supply to aid struggling farmers.', 'Populist Party', 'Greenback Party', 'Libertarian Party', 'Republican Party', 'B', 30),
  ('This Civil War leader was appointed lieutenant general in 1864 and took command of all Union armies.', 'Robert E. Lee', 'Ulysses S. Grant', 'William Tecumseh Sherman', 'George Meade', 'B', 30),
  ('This influential American figure published his first "American Spelling Book" in 1783, long before releasing his famous dictionary.', 'Samuel Johnson', 'Noah Webster', 'Merriam-Webster', 'William Shakespeare', 'B', 30),
  ('In 1875, this notorious political leader escaped from jail, fleeing first to Cuba and later to Spain.', 'Alfred Smith', 'William Magear "Boss" Tweed', 'Richard Croker', 'John Kelly', 'B', 30),
  ('In 1817, Congress divided a large territory that later became two states, nearly identical in size and shape.', 'Georgia and Alabama', 'Louisiana and Mississippi', 'Alabama and Mississippi', 'North and South Carolina', 'C', 30),
  ('The first Mexican-American to serve as mayor of a major U.S. city, he led this Texas city from 1981-1989.', 'Houston', 'Dallas', 'San Antonio', 'Austin', 'C', 30),
  ('This 1786 uprising, led primarily by farmers, took place in Massachusetts and is now known as a major early protest.', 'Whiskey Rebellion', 'Shays\' Rebellion', 'The Civil War', 'Pontiac\'s Rebellion', 'B', 30),
  ('In this election year, the famous campaign slogans "The Moose is Loose" and "Ready for Teddy Again" were used.', '1908', '1912', '1916', '1920', 'B', 30),
  ('This bloody battle, fought in Maryland on September 17, 1862, was the turning point in the Confederate invasion of the North.', 'Battle of Gettysburg', 'Battle of Antietam', 'Battle of Bull Run', 'Battle of Fort Sumter', 'B', 30),
  ('On February 1, 1960, four black students held a sit-in at a lunch counter in this North Carolina city as a protest against segregation.', 'Charlotte', 'Greensboro', 'Raleigh', 'Durham', 'B', 30),
  ('In 1945, this state was the site of the world’s first atomic bomb test, which changed the course of history.', 'Nevada', 'New Mexico', 'California', 'Hawaii', 'B', 30),
  ('In his teenage years, this "pickle king" from Pittsburgh began a business supplying fresh produce to local grocers.', 'Andrew Carnegie', 'Henry Heinz', 'John D. Rockefeller', 'George Westinghouse', 'B', 30),
  ('This tunnel, opened in 1937, was named after a U.S. president and runs beneath the Hudson River.', 'Holland Tunnel', 'Lincoln Tunnel', 'Brooklyn Tunnel', 'Queens Tunnel', 'B', 30),
  ('This mansion in Rhode Island, owned by Cornelius Vanderbilt, features a ceiling painted to resemble a cloud-filled sky.', 'The Marble House', 'The Breakers', 'The Elms', 'Chateau-sur-Mer', 'B', 30),
  ('The first powder mills of this company were established along the Brandywine River in Delaware in 1802.', 'Standard Oil', 'Ford Motor Company', 'DuPont', 'BASF', 'C', 30),
  ('In the 1884 election, the "Never Blaine" Republicans who refused to support the GOP candidate were nicknamed this, from an Algonquian term.', 'Radicals', 'Mugwumps', 'Libertarians', 'Moderates', 'B', 30);
